### PR TITLE
Added fix for considering expiresIn of cache

### PR DESCRIPTION
**Pull request by Mennu**
Session never expires #92

Details : Added a expiredOn while creating a cookie and updated the check condition with the expiredOn.

### CODE REVIEW

**Comment by mark-bradshaw** [comment]
Thank you @Mennu.  I'll take a look.  Meanwhile I notice that the tests are failing.  This could be something you did, or a version issue that needs to be addressed.

**Comment by mark-bradshaw** [comment]
Can you please resolve any failing tests and push your changes?  You can run tests with `npm test`.

**Comment by Mennu** [comment]
Yes mark I am fixing the code will push in the clean code once done.
On 26-May-2016 11:18 PM, "Mark Bradshaw" <notifications@github.com> wrote:

Can you please resolve any failing tests and push your changes? You can run
tests with npm test.

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/hapijs/yar/pull/94#issuecomment-221944092>

**Comment by mark-bradshaw** [comment]
Thank you.

**Comment by mark-bradshaw** [comment]
@Mennu Any word on this?

**Comment by Mennu** [comment]
@mark-bradshaw closing the pull request as tested the session expiration and existing code is working fine, sry for the delay. If its ok i can update the test case and check in.

**Pull request closed without merging**
