### PR TITLE
Migration with hapi v17

### PR DESCRIPTION
**Pull request by MikeBazhenov**
Hi!
I wrote migration and fix all tests for new code style.

It is my first contribute.

### CODE REVIEW

**Comment by hueniverse** [comment]
Thanks. Try to get the CI to pass.

**Comment by mark-bradshaw** [comment]
Hey Mike.  Thanks for the contribution.  One thing that's different now in Hapi v17 is the use of async/await, and that changes up the form of all the tests.  Unfortunately, it's a lot of work, but we'll need to change out all the callback style `server.inject`s with async/await style.  Right now those tests that are marked as passing aren't actually getting to any of the assertions.

So, for instance...

```
server.inject({ method: 'GET', url: '/still_2', headers: { cookie: cookie2[1] } }, (res) => {

  expect(res.result).to.equal('custom_id_2');
  done();
});
```

would change to:

```
const res = server.inject({ method: 'GET', url: '/still_2', headers: { cookie: cookie2[1] } });
expect(res.result).to.equal('custom_id_2');
done();
```

If you feel up to doing those changes that'd be great.

**Comment by MikeBazhenov** [comment]
@hueniverse need to write new test, for 13% of code.

**Comment by MikeBazhenov** [comment]
@mark-bradshaw can you help me, and write test for other 13% code?

And I will be write tests, for new code style

**Comment by mark-bradshaw** [comment]
You might find, Mike, that once you fix the tests so that they are actually going all the way through that you have 100% coverage again.  A lot (mabye all) of that 13% missed coverage is actually due to the tests not completing.

**Comment by mark-bradshaw** [comment]
BTW, I just realized I forgot the `await` on the `server.inject` call, which is needed.

**Comment by MikeBazhenov** [comment]
@hueniverse mission complete!

**Comment by mark-bradshaw** [comment]
Thanks Mike.  I'll take a look.

**Pull request merged**
